/**
 * server.js — Local dev server untuk Fawz Pro
 * Menyembunyikan Supabase key dari source HTML dengan inject via /config.js
 * 
 * Jalankan: node server.js
 * Buka: http://localhost:3000
 */

require('dotenv').config();

const http = require('http');
const fs   = require('fs');
const path = require('path');

const PORT        = process.env.PORT || 3000;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('❌ SUPABASE_URL atau SUPABASE_KEY tidak ditemukan di .env');
  process.exit(1);
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.json': 'application/json',
  '.woff2':'font/woff2',
  '.woff': 'font/woff',
};

const server = http.createServer((req, res) => {
  let urlPath = req.url.split('?')[0]; // hapus query string

  // ── Endpoint khusus: /config.js ──
  // Inject Supabase config dari .env — tidak pernah ada di source HTML
  if (urlPath === '/config.js') {
    res.writeHead(200, {
      'Content-Type': 'application/javascript',
      'Cache-Control': 'no-store', // jangan cache
    });
    res.end(`
// Auto-generated by server.js — DO NOT commit this file
(function() {
  window.__FAWZ_CONFIG__ = {
    supabaseUrl: '${SUPABASE_URL}',
    supabaseKey: '${SUPABASE_KEY}'
  };
})();
    `.trim());
    return;
  }

  // ── Serve static files ──
  if (urlPath === '/') urlPath = '/index.html';
  // Kalau tidak ada ekstensi, coba tambah .html
  if (!path.extname(urlPath)) urlPath += '.html';

  const filePath = path.join(__dirname, urlPath);

  fs.readFile(filePath, (err, data) => {
    if (err) {
      if (err.code === 'ENOENT') {
        // 404 — coba serve 404.html
        fs.readFile(path.join(__dirname, '404.html'), (e2, d2) => {
          res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
          res.end(d2 || '<h1>404 Not Found</h1>');
        });
      } else {
        res.writeHead(500);
        res.end('Server error');
      }
      return;
    }

    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`✅ Fawz Pro berjalan di http://localhost:${PORT}`);
  console.log(`   Supabase URL : ${SUPABASE_URL}`);
  console.log(`   Key          : ${SUPABASE_KEY.slice(0,20)}... (tersembunyi)`);
  console.log(`\n   Tekan Ctrl+C untuk berhenti\n`);
});
